export const ADD_TOAST_MESSAGE = 'ADD_TOAST_MESSAGE';
export const CLOSE_TOAST_MESSAGE = 'CLOSE_TOAST_MESSAGE';

export const OPEN_ALERT_DIALOGUE = 'OPEN_ALERT_DIALOGUE';
export const CLOSE_ALERT_DIALOGUE = 'CLOSE_ALERT_DIALOGUE';
export const OPEN_CONFIRM_DIALOGUE = 'OPEN_CONFIRM_DIALOGUE';
export const ACCEPT_CONFIRM_DIALOGUE = 'ACCEPT_CONFIRM_DIALOGUE';
export const CANCEL_CONFIRM_DIALOGUE = 'CANCEL_CONFIRM_DIALOGUE';

export const SET_LOG_ENTRIES = 'SET_LOG_ENTRIES';
export const ADD_LOG_ENTRY = 'ADD_LOG_ENTRY';
export const UPDATE_LOG_ENTRY = 'UPDATE_LOG_ENTRY';
export const REMOVE_LOG_ENTRY = 'REMOVE_LOG_ENTRY';

export const SET_USER_SETTINGS = 'SET_USER_SETTINGS';

export const SET_READING_SUGGESTIONS = 'SET_READING_SUGGESTIONS';

export const START_DATE_VERSE_COUNT_JOB = 'START_DATE_VERSE_COUNT_JOB';
export const FINISH_DATE_VERSE_COUNT_JOB = 'FINISH_DATE_VERSE_COUNT_JOB';
export const SET_DATE_VERSE_COUNTS = 'SET_DATE_VERSE_COUNTS';
export const SET_ALL_DATE_VERSE_COUNTS = 'SET_ALL_DATE_VERSE_COUNTS';

export const SET_PASSAGE_NOTES_QUERY = 'SET_PASSAGE_NOTE_QUERY';
export const SET_PASSAGE_NOTES_STAGED_QUERY = 'SET_PASSAGE_NOTE_STAGED_QUERY';
export const SET_PASSAGE_NOTES_LOADING = 'SET_PASSAGE_NOTES_LOADING';
export const SET_PASSAGE_NOTES = 'SET_PASSAGE_NOTES';
export const SET_PASSAGE_NOTE_PAGINATION = 'SET_PASSAGE_NOTE_PAGINATION';

export const SET_PASSAGE_NOTE_TAGS = 'SET_PASSAGE_NOTE_TAGS';
export const ADD_PASSAGE_NOTE_TAG = 'ADD_PASSAGE_NOTE_TAG';
export const UPDATE_PASSAGE_NOTE_TAG = 'UPDATE_PASSAGE_NOTE_TAG';
export const REMOVE_PASSAGE_NOTE_TAG = 'REMOVE_PASSAGE_NOTE_TAG';

export const OPEN_PASSAGE_NOTE_EDITOR = 'OPEN_PASSAGE_NOTE_EDITOR';
export const CLOSE_PASSAGE_NOTE_EDITOR = 'CLOSE_PASSAGE_NOTE_EDITOR';
export const UPDATE_PASSAGE_NOTE_EDITOR = 'UPDATE_PASSAGE_NOTE_EDITOR';
export const SET_PASSAGE_NOTE_EDITOR_ERRORS = 'SET_PASSAGE_NOTE_EDITOR_ERRORS';
export const SET_PASSAGE_NOTE_EDITOR_VALID = 'SET_PASSAGE_NOTE_EDITOR_VALID';
